services:
  - type: web
    name: pharmacy-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_DB_URL
        value: <your-supabase-postgres-connection-string>
