services:
  - type: web
    name: pharmacy-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: db.supabase.co
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_username
      - key: DB_PASSWORD
        value: your_password
      - key: DB_PORT
        value: 5432
